### ISSUE TITLE
Milestone: Contract Bidding

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#161]
# Bidding
## Backend

- [x] Submission of a bid adds the user to the pending bids opening them up to be rejected or accepted
- [ ] Passing that information into the bid so that the owner can view the changes proposed
- [ ] An option to Reject the changes and counterproposal to them.
