### ISSUE TITLE
Milestone: Fleet Manger

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#162]
# Fleet Manager
## Backend

- [ ] User's fleet table should pull ships and their default settings from the DB as an item for their Fleet Table
- [ ] Make the user able to change the components and weapons on the ship
- [ ] Allow the user to add items to the cargo of the ship (probably allow the user to go over the SCU Total of the ship and give a warning or something on the front end)
- [ ] Make a roles table for all the ships dependent on class (Will have to go through a lot of ships to set this up custom probably dependent on what the ship has - Can make this a separate issue and come back to it)
- [ ] Allow user to add custom roles to their Role table for ships
- [ ] Base level data for ships
- [ ] Users that are assigned to roles
- [ ] Allow roles to have permissions to access different tables or parts of tables for given ship (I.E. Cargo, Given Turret Ammo count, Bringing components offline and online)
