### ISSUE TITLE
Milestone: Contract Manager

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#163]
# Contract Manager
The following things need to be setup within the backend for the front end Contract Manager

- [x] Location Data on a contract 
- [x] Allowing the Contract owner to add locations and to turn off access to locations
- [x] Reading Contractors locations to allow the user to passed to locations attached to the Contract
- [x] Accepted Contractors Table with the data for it needed including their roles, payclass, current pay and permissions
- [x] Fleet Allocation table as a reference table to know what ships are participating
- [x] A group data point to group together ships for better organization
- [x] The payroll table to include all the number array data for payments and payroll and profits for everything laid out in the Frontend issue
