### ISSUE TITLE
Update: Popup - UI/UX Refactor

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#186]
# Update: Popup @Contract Manager - UI/UX Refactor
**Brief**
> Need to implement Create Contract UI/UX Validation, Flow Refactor, Bug Fixes
#### Contract Details
- [x] #252 
#### Locations
- [x] #257 
#### Contractors
- [x] #258 
#### Payroll
- [x] #253 
### Expected
*none*
#### Contract Details
- [x] Title Field Goes to error when limit reached
- [x] Scrollable Archetype list limiting the subtype selection
- [x] Bring Emergency Button to Details Screen
#### Time Information
- [x]  Bid Date shouldn't be after Start Date or end Date
- [x] Start Date shouldn't be before Bid End Date or after End Date
- [x] End Date shouldn't be before Start Date or before Bid Date
- [x] Toggle between manual or Automatic
#### Contract Details
* Break into two Columns
* Title over briefing
* New Archetype Scroller in right at top
* Autocomplete
* New emergency button underneath
#### Time Information
* Toggle Selection at the top
* Notation underneath that Unselected times blah blah
* All boxes in row
* Notate in the time selection that all times are in local tz
* Start Box under start date
#### Contractors
* flip sides
#### Payroll
* Move Options below Pay Structure & Default (Row)
## Attachments
*none*
## Logs
*none*
## Code File &/|| Block
*none
#### Milestone
#69 
> VerseLedger 1.0 - MVP
