### ISSUE TITLE
Milestone: Contract Manager

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#274]
# Milestone Feature: Contract Manager
## Purpose
The Contract Manager is an App on the Personal Ledger where an individual goes to interact with actual contracts that they own or have accepted.
### Contract Browser
- [x] Tabs for the Contract Browser that filter the contract list
- [ ] A Search Tool Bar that is capable of filtering the displayed contracts
- [x] Contract Cards to Display Limited detail and allow the selection of a contract
- [x] Pagination to switch between pages of contracts display
#### Statistics Page
- [ ] User Ratings Breakdown
- [ ] Contractor History Summary
- [ ] Employer History Summary
- [ ] Recent Performance & Ratings
#### Contract Manger
- [ ] Organized Top Box Displaying relevant information with Popups needed to explain more detail
- [x] Locations Display & Briefing Display (Make Briefing Collapsible?)
- [x] Contractors Tab to Invite users and manage contractors or just display the bids if you are a contractor
- [x] Contract Controller to Manage Bid Status or Contract Status
## Functionality
Breaks down into two areas:
* The Contract Browser
* Selected Contract manager.
### Contract Browser
The Contract Browser searches through Fetched Contracts that match the criteria of the Selected Tab.
#### Tabs
Tabs include:
* Accepted
Shows the Contracts the user has an accepted bid for that are currently still active.
Also shows in a seperate section Contracts the user as a bid status of expired where the contract is still active
* Owned
Shows the Contracts the user is the Contract Owner for that are currently still active
* Pending
Shows the Contracts the user has submitted a bid for that has a status of Pending where the contract is still active.
* ~~Offers~~ Invites
Shows the Contracts the user has a bid status of Invited on that are still active.
* History
Shows the Contracts that are currently Completed in status where the User was the Contract Owner had a bid where their status was either accepted or expired.
#### Tools
The Tools will be a drop down section which allows the user to filter through contracts.
This will include a Filter buttons for certain filters, A sort by box, & a search box.
#### Contract Cards
The Contract Cards are buttons that can be clicked on in order to select a contract that display a limited amount of Information.
#### Pagination
The Pagination Bar will stick to the bottom to allow the user to sift through pages of contracts in a particular Tab/
### Selected Contract Manager
The Selected Contract Manager is where contracts are actually controlled, as well as bids on them. 
When Unselected, the screen should give a statistics breakdown for the user to see.
After the user selects a contract, we will be greeted by a screen with varied controls and displays.
#### Main Info
The Top Box should contain the main information including:
* Contract Owner
* Title
* Status
* Subtype
* Archetype
* Pay Structure
* Contract Start Time || Bid Time End
* Time Remaining on the Contract
#### Additional Details
* Locations
* Briefing
#### Contract Activity Controller
The Activity Controller should be broken down into 3 Tabs to be able to manipulate more indepth data on the Contract.
##### Contractors
This is where the Contract Owner can Invite Users, Accept || Decline bids, Dismiss Contractors, and quickly view who is currently involved on the Contract.
This should have a filter button that allows the user to filter through the Bid Statuses.
The Contractor can use this Screen in Order to see who is currently involved in the contract and bidding on it.
##### Payroll
***Schedule For a Later Update***
This is where the Contract Owner can Overview information Regarding Money on the contract, It will be broken into 3 subsequent tabs:
* Overview
Shows an interactive chart for Contract Owner & Contractors to see the performance on the Contract
* Revenue
This Shows the Recieved cash during the contract including sales and payouts.
* Costs
This shows the Payments made during the contract subtracting from the total as well as the Contractors Total pay per contractor.
Below the tabs section there will be a Floating control button in order to allow the Contract Owner to open a Popup to add or remove data points from the contract.
##### Ships
***Schedule For a Later Update***
Here is a screen much like the Contractors screen where users can interact with different ships on the Contract and join them, or request to add ships to the contract.
This will be a Scrollable list where the Contract Manager has a control to add ships manually, or request Contractors to add their ships within their own fleets. 
Contractors will also have an option to Submit a request to add one of their ships.
When a ship is added by the Owner, the Owner will have an option to invite users to join that ship at different capacities.
The Contract Owner will have to Invite someone to Captain that ship if they are already captaining a ship added on the contract, else they will be prompted to Switch active ships to captain the selected ship.
Contractors will be set to Captains of their own ships that are added to the contract, and in the same manner extras will require an invite of a captain. 
In the actual list, Contractors will be able to Request to join ships that are in the List and select what capacity they wish to join as.
#### Contract Controller
The Contract Controller is where you trigger status'.
##### Contract Owners
Contract Owners Will have Buttons available to them depending on the Status of the Contract.
Always available will be:
* Cancel Contract
Sets the contract status to canceled And prompts the Users to rate the contractors and the contractors recieve a notification to rate the employer
* Edit Contract
Brings up a prefilled Create Contract Screen where the Contract owner can edit details regarding the Contract.
Then when Contracts are in Certain Status', the Controls displayed will vary.
When the Contract is in a Bidding Status It will Show End Bidding & Start Contract
When the Contract is in a Pending Status it will show the Start Contract
When the Contract is in an InProgress Status it will show the Complete Contract
* End Bidding
This Will set the contract Status to pending While it waits for the Contract to start
* Start Contract
This Will set the Contract Status to InProgress till the End Date
* Complete Contract
This WIll Set the Contract Status to Completed
##### Contractors
Contractors will have buttons to Control their Bid Status Where Applicable.
If the Contractor Had a Pending Bid Status:
* Cancel Bid 
This Sets the Bid Status to Expired
If the Contractor has an Active Status:
* Withdraw
Sets the Contract Status to Expired
If the Contractor has an Expired Status:
* Resubmit Bid
This Sets the Bid Status to Pending
#### Notifications
* Notifications on Contract Completion or Withdraw from active will be sent out for people to submit Ratings
 * To Owner & Contractors
* Notifications when A Contract Bid has been accepted
 * Notification to Contractor
* Notification for Contract Reject
 * Sent to Contractor
* Notification for Newly Set pending Status
 * Sent to contract owner of pending bid

*Add Comments below to make further suggestions, to link Commits resolving needs, Updates that link to certain needs, or to attach bugs to this feature during this milestone*
