### ISSUE TITLE
Milestone: Contract Bidding

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#314]
# Contract Bidding
### Backend
- [x] Bargaining System
- [x] Endpoint for Sending & Patching Offers on Pay
- [x] An update to the Bid Table to Allow Contractors to Have specific Pay attached. (Would be useful to make it to a history table or something that allows us to accumulate pay over time to that user. Like If I wanted to see a chart and just keep adding pay when we work on a payroll. If that's too much for V1 then it's fine, but we should set the tables up in a way that wont break when we migrate to a new payroll system
### Frontend
- [x] Update the Popup UI of Submit Bid Styling
- [x] Create Form Fields for Negotiable Contract
- [x] Update the Contract Manager UI for Bids with Negotiations
- [x] Use the Bid popup to display Offer or & accept or make counter offer

## Functionality
This System is needed in order to pass bids to the Contract Owners.
The Process of a Non Negotiable Contract is simply just a Posting of a Contract Bid with a Pending Status.
However, when a contract is set to negotiable, the player needs to be able to submit a form with requested changes to the contractor pay.
* Default Pay: The Default Pay should be Negotiable on a Per Contractor Basis which allows Some Contractors to be paid different amounts (This leads into another Caveat)
* Notes: Additional notes attached

We can check if `PENDING` && if `bid.pay`.
The User should then get a Popup with the Proposals.
Now we can either have a flat out reject or Accept, or create a counter proposal system where the Contract Owner can click on a checkbox to approve certain changes and change other fields and submit which sets the user to an Invite Status with a patched bargain? Something along those lines. But we wouldn't really have a way to check which fields have changed to allow the user to understand what terms have been accepted.
We should probably prevent this repetition for a count of 2 times to prevent issues.
Alternatively, we could also add the Messaging System and give the players an option to message each other after a bargain has been started to have a workaround for back and forth negotiation.

This also means that we need to update the Bid system to allow for a custom Pay Field per User. Default Pay Is what it automatically recieves, but this can be updated by the Contract Owner or an Accepted Bargain
