### ISSUE TITLE
Milestone: Create Contract

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#69]
# Create Contract Modal
The Shell components for the Create Contract Screen have been inserted. Now it needs Styling, Formatting, and hooked up to the backend.
## Front End

- [x] Form Formatting -  Need to pretty up the pages and the Formatting for all the Form Pages.
- [x] Style the Page Control Buttons
- [x] The Page data is not saved going from page to page, need to save the data to a state before submit
- [x] Add a Snackbar alert at the bottom of the App Page for when submit has gone through for the progress portion & the completed event
