### ISSUE TITLE
Milestone: Contract Bidding

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#70]
# Contract Bidding
Contract Bidding Dialog has not been added. Contract Bidding is the process for when the user bids on a contract and is presented with options if they would like to change some items on the contract when bidding.
## Frontend
The Bid Screen is a dialog that is opened when the Bid button is clicked within the Contract Details Screen. There will be a few conditionals on what can be changed on the bid depending on how it is setup.

- [x] Create the dialog to submit a bid to a contract
- [x] An option to negotiate the payout of the bid
- [x] An option to negotiate the start location of the bid
- [x] An option to negotiate the duration of the bid
- [x] An option to insert comments on a bid.
- [x] An option to add their ship to the fleet allocation 
- [x] An option to join an already added ship to the fleet allocation
- [x] A submit button to submit the bid
- [ ] Hook up the datafields to the front end
- [ ] Create a state to pass the negotiation data back
- [ ] Pass the user id back as the bidder
