### ISSUE TITLE
Milestone: Location Explorer

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#73]
# Location Explorer
The Location Explorer is a tool that will be utilized for people to find out information about various locations, report crimes to an area, and to quickly navigate to different parts of the app passing in that location as a param.

- [ ] Style & Format (After Featureset Below)

## Set Location
Should automatically be set to the current location
- [ ] Autofill location selection tool reused here from the location selection without the control buttons from the set global location button component.
## Location Data
Here we want to utilize the data  from the Fleetyards API & VerseTime, as well as our own DB to give needed info
- [ ] Local Time should display the ingame time at that location
- [ ] StarRise Time is for when that location's sun will rise
- [ ] Starset time same
- [ ] :OnHover for the times should show the converted user's System Time. Might also want to add "time till" info
- [ ] Jurisdiction to let the user know who's Jurisdiction this location is in. Hovering over could also let the user know if there is an Armistice Zone
- [ ] Safety rating should take in reported crimes to an area over a one week period with a trailing average and compare them to other places.

> Safety Rating should be a percentile Step. 
> 1. Benign - 90th+ Percentile
> 2. Safe - 75th+ Percentile
> 3. Moderate - 50th+ Percentile
> 4. Unsafe - 35th+ Percentile
> 5. Dangerous - 20th+ Percentile
> 6. Extreme Risk - 10th+ Percentile
> 7. Crime Ensured - 1st+ Percentile

- [ ] Population Graph: Mui Sparkline Graph showing daily Population average points
- [ ] Might want to have a toggle button group to switch between different time ranges
- [ ] Daily crime Box should show the highest committed crime and the amount of those reports for the particular day.
- [ ] Surface elevation of the location
- [ ] Avg temp of that location
- [ ] Hazards should show radiation, potential issues with animals and other relevant data
- [ ] Gravity of that location
- [ ] ATM with a warning symbol in the event the Atmosphere composition is not breathable
- [ ] Amenities should show all the different POI's of the given area pulled from something like cornerstone
- [ ] Shops should show the Shops in that area
## Ark Map
This is a box that we can implement the ArkMap inside of and link it to the location selection as well
- [ ] Ark Map Render
- [ ] Linking in the Ark Map to location selection and vice versa?
## Location Controls
- [ ] Set Location Button: Setting your current location to selected location (Should bring up a verification dialog)
- [ ] View Logisitics Button: Should navigate to the Logistics App with the Selected location set as param
- [ ] View Market Button: Should just bring up a In construction modal with Contribution Buttons for project support
- [ ] Report Crime Button: Brings up a dialog to report a crime with a selection for a type of crime and prefilled date with an option for the person to update the date and also give an option for the user to change their location and also set their ship as destroyed quickly
