### ISSUE TITLE
Milestone: Overview App

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#74]
# Overview App
This provides an overview of the most important information for the user with quick navigate buttons.
## Notification Box
- [x] Link to the user's notificaitons
## Radio Frequencies
- [x] Rename to SCRadio or Radio Tuner or something
- [x] Bring to a smaller size
- [x] Link into several webplayers for audio music and make it play throughout the app
- [x] Create a popup webplayer that's movable with controls when turned on
- [x] Source button should take to that Radio's website for support and various other things. Tab should be auto muted if able
## Job Overview
- [x] Add a small overview box for open jobs Within the different apps (I.E. Contracts, Refining, Market [later]) for quick navigation
## Location Explorer
- [x] Style and Format
- [x] Finalizing what info displays in the overview
