### ISSUE TITLE
Milestone: Logistics App

### ISSUE THREAD

**Issue by ThreeCrown** [MandaCorpNetwork/verseledger#76]
# Logistics App
This is pretty much just a copy of the NikNax app in SC
## Selection
- [ ] Toggle Button to switch between selecting Locations or Ships
- [ ] Link in the selection components
## Manifest Table
Table View that lists out all the items at a location.
- [ ] Item Name
- [ ] SCU Count
- [ ] Type
- [ ] Location Breakdown if higher in the hierarchy of location chain
- [ ] Move button which brings up a dialog to move an item manually to another location. Should default to the currently selected ship to quickly load onto the ship
- [ ] Add a multiselect checkbox which moves the move and offload button to the top bar to mass move
- [ ] Offload button to delete item from the list or mark it as sold with a dialog box
## Item Display
- [ ] Box on the right to display the information on the selected Item.
